apiVersion: apps/v1
kind: Deployment
metadata:
  name: btc-electrum-test
  namespace: test
  labels:
    app: electrum-test
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: electrum-test
  template:
    metadata:
      labels:
        app: electrum-test
    spec:
      volumes:
        - name: wallet-volume
          persistentVolumeClaim:
            claimName: pvc-electrum-wallet
      containers:
      - name: electrum-test
        image: {{IMAGE_NAME/TAG}}
        imagePullPolicy: Always
        ports:
          - containerPort: 7777
        env:
        - name: NETWORK
          value: --testnet
        - name: ELECTRUM_SERVER
          value: -s {{ELECTRUM_PRIVATE_SERVER}}
        volumeMounts:
          - mountPath: /root/.electrum/testnet/wallets/
            name: wallet-volume

