apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-electrum-wallet
  labels:
    app: electrum-load
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
  namespace: test
spec:
  storageClassName: "gp2-enc"
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
